name: Precompute dashboards
on:
  push:
    paths:
      - 'data/processed/**'
      - 'tools/precompute.py'
      - '.github/workflows/precompute.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install numpy pandas statsmodels plotly
      - name: Run precompute
        run: |
          python tools/precompute.py
      - name: Commit artifacts
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add assets/prebuilt/*.json
          git diff --staged --quiet || git commit -m "precompute: refresh prebuilt JSON"
          git push
